### ISSUE TITLE
Remove x/staking from testapp

### ISSUE THREAD

**Issue by joshklop** [polymerdao/monomer#221]
In our testapp, we currently use:

- `staking`
- `bank`
- `account`

Can we remove one or more of these?

**Comment by natebeauregard** [comment]
I did some research and I can't think of a reason why we need the staking module. The staking module is specifically designed for proof of stake chains where the chain's validators and delegators stake tokens to secure the network.

Since we're operating as an L2 with a different consesnsus mechanism, I feel like the staking module is unnecessary to include in our testapp.

I tried removing the staking module from our testapp and verified that the e2e tests and x/rollup integration test still pass.

The staking module was added in [PR #1](https://github.com/polymerdao/monomer/pull/1/files#diff-8bb3e8b2cf738b69b8c09782ce029695d5b3f74e526ca9ede01d50a4f8958f62R68). We recently [removed the mint module](https://github.com/polymerdao/monomer/pull/155) since it was unnecessary, I feel like we could do the same for `x/staking` and just remove it.
